# Copyright 2023 Kapeta Inc.
# SPDX-License-Identifier: MIT

defaultValue:
  fieldA: "Some value"
  fieldB: 42
schema:
  type: object
  required:
    - fieldA
  properties:
    fieldA:
      type: string
    fieldB:
      type: number
uiSchema:
  fieldA:
    "ui:autofocus": true
  fieldB:
    "ui:widget": range
