$id: /core/deployment-target
$schema: http://json-schema.org/draft-07/schema#
type: object
properties:
  kind:
    type: string
    const: core/deployment-target

  metadata:
    $ref: /core/type-metadata

  spec:
    type: object
    properties:
      configuration:
        $ref: /core/type-schema

