kind: core/deployment
metadata:
  name: blockware/test-deployment
  title: Test deployment
  description: This is a deployment to the test environment
spec:
  environment:
    ref: blockware/test:1.0.0
  target:
    kind: blockware/deployment-target-gcp:1.0.0
  services:
    - name: blockware/todo-web:1.0.0
      artifact:
        name: blockware/todo-web
        version: "1.0.0"
        type: docker
      dependencies:
        - blockware/todo-api:1.0.0

    - name: blockware/todo-api:1.0.0
      artifact: 
        name: blockware/todo-api
        version: latest
        type: docker
      configuration:
        USE_TLS: true
      dependencies:
        - blockware/postgres:1.0.0

    - name: blockware/postgres:1.0.0
      artifact: 
        name: postgres
        version: "12.2"
        type: managed
      dependencies: []
