kind: core/concept
metadata:
  name: core/deployment
spec:
  dependencies:
    - spec.environment.ref
    - spec.target.kind
    - spec.services.name
  schema:
    $id: /core/deployment
    $schema: http://json-schema.org/draft-07/schema#
    type: object
    required:
      - kind
      - metadata
      - spec
    properties:
      kind:
        type: string
        const: core/deployment
      metadata:
        $ref: /core/type-metadata
      spec:
        type: object
        required:
          - environment
          - target
          - services
        properties:
          environment:
            type: object
            properties:
              ref:
                type: string
                pattern: ^(\w+://)?[a-z0-9-_]+/[a-z0-9-_]+(:(\d+\.\d+\.\d+|local))$
          target:
            type: object
            properties:
              kind:
                type: string
                pattern: ^(\w+://)?[a-z0-9-_]+/[a-z0-9-_]+(:(\d+\.\d+\.\d+|local))$
            required:
              - kind
          services:
            type: array
            items:
              type: object
              required:
                - name
                - artifact
              properties:
                name:
                  type: string
                  pattern: ^(\w+://)?[a-z0-9-_]+/[a-z0-9-_]+(:(\d+\.\d+\.\d+|local))$
                artifact:
                  type: object
                  required:
                    - name
                    - version
                    - type
                  properties:
                    name:
                      type: string
                    version:
                      type: string
                    type:
                      type: string
                      pattern: '^(docker|managed)$'
                dependencies:
                  type: array
                  items:
                    type: string
                configuration:
                  type: object
