kind: core/concept
metadata:
  name: core/deployment-target
spec:
  schema:
    $id: /core/deployment-target
    $schema: http://json-schema.org/draft-07/schema#
    type: object
    required:
      - kind
      - metadata
      - spec
    properties:
      kind:
        type: string
        const: core/deployment-target

      metadata:
        $ref: /core/metadata

      spec:
        type: object
        required:
          - service
          - logo
        properties:
          logo:
            type: string
          service:
            $ref: /core/remote-service
          configuration:
            $ref: /core/schema

