# Copyright 2023 Kapeta Inc.
# SPDX-License-Identifier: MIT

kind: core/deployment-target
metadata:
  name: some-handle/my-deployment-target
  title: My Deployment Target
  description: This allows you to introduce a new deployment target
spec:
  icon:
    type: url
    value: https://storage.googleapis.com/cdn-public-kapeta/logos/google_cloud_logo.png

  service:
    apiVersion: 1.0.0
    url: https://deployment-target-gcp.externals.kapeta.com

  configuration:
    uiSchema:
      zone:
        ui:widget: radio

    schema:
      type: object
      properties:
        zone:
          type: string
          enum:
            - asia-east1-a
            - asia-east1-b
            - asia-east1-c
            - asia-east2-a
            - asia-east2-b
            - asia-east2-c
            - asia-northeast1-a
  operators:
    kapeta/resource-type-mongodb:
      title: MongoDB Cluster
      description: MongoDB cluster deployment
      icon:
        type: url
        value: https://storage.googleapis.com/cdn-public-kapeta/logos/mongodb.png
      link:
        type: url
        value: https://www.mongodb.com/
      configuration:
        schema:
          type: object
          required:
            - fieldA
          properties:
            fieldA:
              type: string
            fieldB:
              type: number
    kapeta/resource-type-postgres:
      title: CloudSQL Postgres
      description: Postgres as a service - from Google Cloud Platform
      icon:
        type: url
        value: https://storage.googleapis.com/cdn-public-kapeta/logos/google_cloud_logo.png
      link:
        type: url
        value: https://cloud.google.com/sql/
      configuration:
        schema:
          type: object
          required:
            - fieldA
          properties:
            fieldA:
              type: string
            fieldB:
              type: number




