kind: core/concept
metadata:
  name: core/environment
spec:
  dependencies:
    - path: spec.plan.ref
      type: Plan
    - path: spec.deploymentTarget.ref
      type: Deployment target
    - path: spec.services.ref
      type: Services
  schema:
    $id: /core/environment
    $schema: http://json-schema.org/draft-07/schema#
    definitions:
      BlockServiceConfiguration:
        type: object
        required:
          - consumerId
          - serviceId
          - port
        properties:
          consumerId:
            type: string
          serviceId:
            type: string
          port:
            $ref: '/core/port'
      EnvironmentService:
        type: object
        required:
          - id
          - ref
          - kind
        properties:
          id:
            type: string
          ref:
            type: string
          title:
            type: string
          kind:
            type: string
          configuration:
            type: object
            additionalProperties: true

      DeploymentTargetConfiguration:
        type: object
        required:
          - ref
        properties:
          ref:
            type: string
            pattern: ^(\w+://)?[a-z0-9-_]+/[a-z0-9-_]+(:(\d+\.\d+\.\d+(-[a-z0-9][a-z0-9_-]*)?|local))$
          configuration:
            type: object
      BlockInstanceConfigurations:
        type: array
        uniqueItems: true
        items:
          type: object
          required:
            - id
          properties:
            id:
              type: string
            configuration:
              type: object
              additionalProperties: true
            services:
              type: array
              items:
                $ref: '#/definitions/BlockServiceConfiguration'
      PlanConfiguration:
        type: object
        required:
          - ref
          - blocks
        properties:
          ref:
            type: string
            pattern: ^(\w+://)?[a-z0-9-_]+/[a-z0-9-_]+(:(\d+\.\d+\.\d+(-[a-z0-9][a-z0-9_-]*)?|local))$
          blocks:
            $ref: '#/definitions/BlockInstanceConfigurations'
          configuration:
            type: object
    type: object
    required:
      - kind
      - metadata
      - spec
    properties:
      kind:
        type: string
        const: core/environment
      metadata:
        $ref: /core/metadata
      spec:
        type: object
        required:
          - plan
          - deploymentTarget
        properties:
          plan:
            $ref: '#/definitions/PlanConfiguration'
          services:
            type: array
            items:
              $ref: '#/definitions/EnvironmentService'
          deploymentTarget:
            $ref: '#/definitions/DeploymentTargetConfiguration'

