# Copyright 2023 Kapeta Inc.
# SPDX-License-Identifier: MIT

kind: core/environment
metadata:
  name: kapeta/test_env
  title: Test Environment
  description: This is a test environment
spec:
  plan: 
    ref: kapeta://kapeta/sample_java_plan:1.0.0
    configuration:
      awesome_plan: true
    blocks:
    - id: 019bc636-7ba2-5c41-c426-96e90cee21e6
      configuration:
        block-specific: "configuration"
      services:
        - consumerId: myDb
          serviceId: postgres
          port:
            type: mongodb

    - id: 419bc636-75a2-5c41-c426-96e90cee21e6
      configuration:
        block-specific: "configuration"
      services:
        - consumerId: otherDb
          serviceId: mongodb4
          port:
            type: mongodb
  services:
    - id: postgres
      title: Main postgres
      kind: kapeta/resource-type-postgres
      ref: kapeta/resource-type-postgres:1.0.0
      configuration:
        version: POSTGRES_9_6
        tier: db-custom-1-3840
        availabilityType: ZONAL
        storage: 10Gi
    - id: mongodb4
      title: Main Mongo
      kind: kapeta/resource-type-mongodb
      ref: kapeta/resource-type-mongodb:1.0.0
      configuration:
        version: "4.4.17"
        storage: 10Gi
        diskType: premium-rwo
  deploymentTarget: 
    ref: kapeta://kapeta/test-deployment-target:1.0.0
    configuration:
      env: test
      region: us-east-1
