name: Publish to Kapeta Public Repos
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_ARTIFACTORY_SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: 'Install npm for main'
        run: npm install
      - name: 'Generate sources'
        run: npm run generate
      - name: 'Install npm for package'
        run: npm install
        working-directory: ./packages/npm
      - run: npm publish --access public
        working-directory: ./packages/npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

